### ISSUE TITLE
'fxcored tx distribution withdraw-rewards' no longer works after upgrade

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#56] opened 2022-07-21 14:13 UTC
```
$ fxcored tx distribution withdraw-rewards fxvaloper1... --from myaccount --gas-adjustment=1.5 --gas-prices="4000000000000FX" --yes --keyring-backend test --commission
Error: myaccount.info: key not found

$ fxcored keys list --keyring-backend test
- name: myaccount
  type: local
  ...
  algo: eth_secp256k1

$ fxcored version
HEAD-8f2f0f7bf917eac2b405db497a21a0b3c5073f86
```

**Comment by zakir-code** [comment] 2022-07-26 01:49
Duplicate of #54

**Closed by zakir-code** 2022-07-26 01:49 UTC
